### ISSUE TITLE
NM100

### ISSUE THREAD

**Issue by rl102600** [steve1316/granblue-automation-android#1]
App works very well, but when you choose NM 100 it hangs at the selection screen.

**Comment by steve1316** [comment]
Thank you for letting me know. I will take a look at it once GW starts back up.

**Comment by steve1316** [comment]
Just updated the application to fix the cases where you would get stuck trying to start NM100 and NM150. Let me know how it goes!

**Comment by rl102600** [comment]
Works perfectly, thanks!
