### ISSUE TITLE
Accessibility issue

### ISSUE THREAD

**Issue by lEarthLordl** [steve1316/granblue-automation-android#11]
Any idea why the app suddenly stop working randomly? The accessibility for the app keep malfunction after a certain time. Not sure if its my phone issue or the app.

**Comment by steve1316** [comment]
Its the fault of the app. Basically there is a seemingly undetectable bug that causes the app to crash sometimes and I cannot find what is causing it as segfault errors do not leave behind stack traces. As such, I cannot fix it but will happily accept PR fixes from any kind soul who do manage to figure out what causes this issue.
