### ISSUE TITLE
GW not working

### ISSUE THREAD

**Issue by Ekytfy** [steve1316/granblue-automation-android#13]
Hi, it seems like the app isn't working on current gw possibly because they change the system from using meat to bambo
![Screenshot_20220115_211720_6948ba2d6cf6960c4526b24e4863ae4e](https://user-images.githubusercontent.com/67878387/149624972-a6eabd3b-e7ab-4621-917e-46338cc71c68.jpg)

**Comment by steve1316** [comment]
Just uploaded v3.3.2. Check if the problems occur again and post logs if it happens again.
