### ISSUE TITLE
Lumi malice

### ISSUE THREAD

**Issue by rl102600** [steve1316/granblue-automation-android#14]
Bot stops at quest results.
![Screenshot_20220121-123522_GAA](https://user-images.githubusercontent.com/82386768/150582720-4966ddf3-5ad5-4dfe-9cd8-c3c9e7c46731.jpg)
![Screenshot_20220121-125152_GAA](https://user-images.githubusercontent.com/82386768/150583740-9e9c7bcf-092b-4b77-9f6a-b8e1a130a313.jpg)

**Comment by steve1316** [comment]
Fixed in v3.4.0 👍
