### ISSUE TITLE
cannot start android version

### ISSUE THREAD

**Issue by anzumeguru** [steve1316/granblue-automation-android#19]
[log @ 14_36_12.txt](https://github.com/steve1316/granblue-automation-android/files/8139469/log.%40.14_36_12.txt)
cannot start bot...this is my log

**Comment by steve1316** [comment]
Can you restart the Accessibility Service by toggling it on and off until you get a Toast message appearing at the bottom of the screen saying that the service is now running?

**Comment by anzumeguru** [comment]
ah yeah it can be star now,,thank you...btw it can be loop for battle...or where setting for loopin battle....because after 1 battle it off
