### ISSUE TITLE
Scripts?

### ISSUE THREAD

**Issue by rl102600** [steve1316/granblue-automation-android#2]
Scripts seem to work fine at first, but when the raid finishes the bot crashes.

Here is a screenshot of the error i get. Also one from the script i'm using. Don't know if error is on my part.
![Screenshot_20210518-232844_GAA](https://user-images.githubusercontent.com/82386768/118756617-f0091480-b830-11eb-95df-70486fcbf0cc.jpg)
![Screenshot_20210518-233113_Cx File Explorer](https://user-images.githubusercontent.com/82386768/118756864-71f93d80-b831-11eb-9438-325113bd9c19.jpg)

**Comment by steve1316** [comment]
My bad, that is an oversight on my part. I was able to reproduce the problem. A fix will be out shortly.

**Comment by steve1316** [comment]
Just updated the bot to fix this issue. Let me know how it goes!

**Comment by rl102600** [comment]
Thanks! No more issues here.
