### ISSUE TITLE
ENOENT: Open Failed when trying to select Combat Script

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-android#26]
Hello again, when I try to open a combat script, I get the following error message, even after saving in multiple locations with different file names. Is root required to use combat scripts?

![image](https://user-images.githubusercontent.com/82384904/182459356-5aee4bf6-1a94-40c5-8ba3-0333adde9077.png)

![image](https://user-images.githubusercontent.com/82384904/182459405-35c7aef6-7c73-41b7-bfe9-14734820abb9.png)

![image](https://user-images.githubusercontent.com/82384904/182459455-8bdd177d-a0e9-4379-96f0-d2b717af2b60.png)

**Comment by PortablePanda** [comment]
I tried to move it to the root of internal storage, but it's still pointing towards /data/user/0/com.steve1316.granblue_automation_android/cache/primary:[Enter selected file path here].

From my phone's file manager, the path is /Internal storage/GAA Scripts/12 Punch.txt.

**Comment by steve1316** [comment]
Moving the scripts to /Internal Storage/ should work. It should not be inside any other folder.

I will look into the issue when I have time. Something to do with converting the URI to actual file path that it thinks the file exists inside the app's cache folder instead of using the actual file path.

**Comment by PortablePanda** [comment]
Yep, moving to /Internal Storage/ worked! Ty for the troubleshooting, I'll just give all of my scripts a prefix to organize them in the meantime.

**Comment by steve1316** [comment]
Took a look at how to solve it, but turns out that Android 11 added a storage restriction for reading files. So unfortunately, leaving the script files in `/storage/emulated/0/` will be the way to go. Updated the description of the Combat Script select button to clarify this.
