### ISSUE TITLE
Combat Scripts can't be deselected

### ISSUE THREAD

**Issue by Ekytfy** [steve1316/granblue-automation-android#28]
Console Warning : 
![Screenshot_20220927_071301](https://user-images.githubusercontent.com/67878387/192447178-877c5362-be95-4f6a-9e4b-29e5333df672.jpg)

**Comment by steve1316** [comment]
Put your combat scripts in `/storage/emulated/0/` and try again.

**Comment by Ekytfy** [comment]
Sorry I mean I can't deselect them, all of the combat scripts are working but I can't deselect them in the selected options

**Comment by steve1316** [comment]
Fixed in v3.8.1.
