### ISSUE TITLE
android version not working

### ISSUE THREAD

**Issue by masayuki232** [steve1316/granblue-automation-android#6]
![Screenshot_2021-09-04-06-26-20-83_6948ba2d6cf6960c4526b24e4863ae4e](https://user-images.githubusercontent.com/89802173/132066956-ce67c375-955d-40d7-8493-1c3b61af4f9e.jpg)
the bot cant seems to work on my android device. using oppo a5 2020 running android 10 . tested on skyleap, chrome and apps. says it cant find the home button.

**Comment by steve1316** [comment]
It seems that your device is 720 pixels in width. I will get to work supporting that screen width as soon as I have some free time.

**Comment by steve1316** [comment]
Just updated the bot to v2.5.1 and added preliminary support for devices like yours with 720p in width.

In addition, I included a new setting that will allow you to set your own image scale. You can find out your scale by taking a screenshot directly on your device and then pick a easily recognizable image asset from the /images/folder in this repository and scaling it until it relatively matches the size of the asset in your screenshot. Whatever percentage you scaled the image asset by will be the number that will go into this new setting.

Let me know how it goes!

**Comment by masayuki232** [comment]
![Screenshot_2021-09-06-14-53-43-32_6948ba2d6cf6960c4526b24e4863ae4e](https://user-images.githubusercontent.com/89802173/132167344-4a648878-ecbb-4034-8928-49cb3358450c.jpg)

just tried and got this error.

**Comment by steve1316** [comment]
Hmm, so the scales of 0.65, 0.67 and 0.69 does not seem to work for your 720p screen. Can you go to the Settings page and set your custom scale starting from 0.50 and working your way up to something like 0.95 going 0.02 at a time and repeatedly running the bot until it actually detects the HOME button? After that, post the scale that worked for you here and I will update the bot to create a range from your scale.

**Comment by masayuki232** [comment]
sure , will update later

**Comment by masayuki232** [comment]
![Screenshot_2021-09-06-16-27-44-17_6948ba2d6cf6960c4526b24e4863ae4e](https://user-images.githubusercontent.com/89802173/132177269-de3c3cc2-a51d-4d82-aa58-35e3326a399b.jpg)



fyi, the error shows up different when i set up ths custom scale. perhaps by chance the 1st error isnt related to the screen scale?

**Comment by steve1316** [comment]
What dooms it all is that it failed to find the HOME button in the first place and a cascade of failures led it to stop there when it attempted to open the Menu to find the Event banner. That cascade is caused by the fact that the bot cannot find match any image assets at all on your screen.

I thought I had the solution by just simply resizing a screenshot from my device to match your screen dimensions and obtaining the scales from there, but I'm ultimately not sure. But I do know the method works as that was what I did to support my Tab S7 tablet.

**Comment by masayuki232** [comment]
thanks for the hard work. for more information, i also tried setting custom scale as instructed, from 0.5 to 1.0 going 0.02 each time. still have no luck

**Comment by masayuki232** [comment]
![Screenshot_2021-09-06-16-56-53-51_6948ba2d6cf6960c4526b24e4863ae4e](https://user-images.githubusercontent.com/89802173/132181204-230b9314-475e-4431-8f78-2c1c54767499.jpg)

setting to 0.67  makes the bot confirm the location at home but cant find home menu button

**Comment by steve1316** [comment]
Oh thats weird. Can you set the confidence of single match and multi match lower than their default 80%? Maybe 75% or 70%?

**Comment by masayuki232** [comment]
![Screenshot_2021-09-06-16-59-08-53](https://user-images.githubusercontent.com/89802173/132181531-d1519849-ae3f-44e2-948f-dee3ba43b21b.jpg)
this is my home screen

**Comment by masayuki232** [comment]
setting confidence from 80 to 70 have no result.

**Comment by kevin01523** [comment]
> Hmm, so the scales of 0.65, 0.67 and 0.69 does not seem to work for your 720p screen. Can you go to the Settings page and set your custom scale starting from 0.50 and working your way up to something like 0.95 going 0.02 at a time and repeatedly running the bot until it actually detects the HOME button? After that, post the scale that worked for you here and I will update the bot to create a range from your scale.
> 
> EDIT: Initially when I created the scales of 0.65, 0.67 and 0.69 for 720p, I resized my own device's screenshot from 1600x2560 to 720x1080 and then resized my image asset of the Attack button by 67% to match what was on my screenshot.

finding the scale kinda hard to figure out

just asking what app etc you are using to resize compare the images at.

**Comment by steve1316** [comment]
Just updated the bot to v2.5.2 with more detailed debugging messages and a new setting called `Enable Test for Home Screen` under the Misc section of the Settings that will test your device compatibility and if the current scale(s) failed, it will automatically find you a scale that works for you. @masayuki232 Let me know how this test goes for you!

@kevin01523 I took a screenshot from my phone and sent it to my computer. Then I opened IrfanView, a third-party alternative to the basic Windows Photo Viewer, and resized it by a certain percentage in Image->Resize/Resample. But now I have included a test that automatically finds the best scale for you, you no longer need to manually do this anymore.

**Comment by masayuki232** [comment]
![Screenshot_2021-09-07-10-52-51-02_6948ba2d6cf6960c4526b24e4863ae4e](https://user-images.githubusercontent.com/89802173/132272379-56cf309a-4816-49b4-b4ec-830e8b609e56.jpg)
 
![Screenshot_2021-09-07-10-50-55-00_6948ba2d6cf6960c4526b24e4863ae4e](https://user-images.githubusercontent.com/89802173/132272381-dad21360-2eff-486d-bdb4-372aa3fcb7de.jpg)
the test worked but still got error when i set the custom scale to 0.65 as instructed

**Comment by steve1316** [comment]
Can you take a screenshot of what happens after you tap the MENU button and post it here?

**Comment by masayuki232** [comment]
![Screenshot_2021-09-07-14-06-26-65_6948ba2d6cf6960c4526b24e4863ae4e](https://user-images.githubusercontent.com/89802173/132287325-7965d7f7-eda1-4427-9a73-85a5b9844ed5.jpg)
it worked normally if i press the menu button then start the bot

**Comment by steve1316** [comment]
Hmm, that is interesting. Is it consistently working after you yourself press the MENU button before starting the bot or is it also now working without you needing to do that?

**Comment by masayuki232** [comment]
![Uploading Screenshot_2021-09-07-15-40-36-38_6948ba2d6cf6960c4526b24e4863ae4e.jpg…]()

**Comment by masayuki232** [comment]
![Uploading Screenshot_2021-09-07-15-40-36-38_6948ba2d6cf6960c4526b24e4863ae4e.jpg…]()

**Comment by masayuki232** [comment]
![Screenshot_2021-09-07-15-40-36-38_6948ba2d6cf6960c4526b24e4863ae4e](https://user-images.githubusercontent.com/89802173/132296725-e1314b6e-9eaa-42fc-aeca-9481e8406dbb.jpg)

**Comment by kevin01523** [comment]
@masayuki232 try clearing data and reset the app after it crashes it might run after that i do experience this often too also move the play or the start button for the bot where it doesn't cover any buttons

**Comment by steve1316** [comment]
User confirmed working after v2.5.3 update.
