### ISSUE TITLE
coop not working???

### ISSUE THREAD

**Issue by uhnini** [steve1316/granblue-automation-android#7]
hi !! im using bluestacks 4 with gaa and for some reason its not letting me start with it? when i try to pick a coop battle to farm its just a blank pop up and i can't choose anything 

![image](https://user-images.githubusercontent.com/65455930/136139201-9abcac19-556e-4183-813c-5234eb8c70da.png)

**Comment by steve1316** [comment]
Confirmed the issue on my end. A fix will be out soon.
